name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  device_info_plus: ^11.1.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/puntos_turisticos.txt
    - assets/images/PT1.png
    - assets/images/PT22.png
    - assets/images/1 RUTA DE ACCESO A TARATA/20240420054308_IMG_6412 (1).jpg
    - assets/images/1 RUTA DE ACCESO A TARATA/Captura de pantalla 2024-09-30 094247.png
    - assets/images/1 RUTA DE ACCESO A TARATA/20240420055036_IMG_6421 (1).jpg
    - assets/images/1 RUTA DE ACCESO A TARATA/WhatsApp Image 2024-09-30 at 15.09.40.jpeg
    - assets/images/2 SENDERISMO/[000789] (2).jpg
    - assets/images/2 SENDERISMO/Cuevas de Quala Quala.png
    - assets/images/2 SENDERISMO/20240315105831_IMG_2472.jpg
    - assets/images/3 RELAJAMIENTO/20240219162533_IMG_0855.jpg
    - assets/images/3 RELAJAMIENTO/458972257_919413446892029_6951314521824928962_n.jpg

