name: tarea2_geolocalizacion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  device_info_plus: ^11.1.0
  provider: ^6.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.0.11
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.0.20 
  flutter_cache_manager: ^3.3.0
  flutter_map_mbtiles: ^1.0.3
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_lints: ^4.0.0
  google_maps_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_maps_flutter: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - "assets/images/1 RUTA DE ACCESO A TARATA/"
    - "assets/images/2 SENDERISMO/"
    - "assets/images/3 RELAJAMIENTO/"
    - assets/marcador.png
